name = "A3VR — Arma 3 Hybrid VR";
picture = "";
logo = "";
logoOver = "";
tooltip = "A3VR Hybrid — Experimental OpenXR bridge";
tooltipOwned = "A3VR Hybrid — Experimental OpenXR bridge";
overview = "Experimental OpenXR presentation, FreeTrack head tracking, motion-controller input and controller-absolute proxy weapons for Arma 3. PiP optics and independent hands are not included.";
author = "A3VR contributors";
version = "1.0.2";
